### ISSUE TITLE
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')

### ISSUE THREAD

**Issue by zaro** [Fatal1ty/aiofcm#1]
I am using the module to send messages from aiohttp application and it works, but there is something strange. After each message send I get the following exception:

```
DEBUG:aiofcm:Closing connection <aiofcm.connection.FCMXMPPConnection object at 0x105179b70>
WARNING:aiofcm:Stream of <aiofcm.connection.FCMXMPPConnection object at 0x105179b70> destroyed:
DEBUG:aiofcm:Connection <aiofcm.connection.FCMXMPPConnection object at 0x105179b70> discarded
INFO:aiofcm:Connection released (total: 0)
ERROR:asyncio:Fatal read error on STARTTLS transport
protocol: <aioxmpp.protocol.XMLStream object at 0x10517f748>
transport: <aioopenssl.STARTTLSTransport object at 0x10517f7b8>
Traceback (most recent call last):
  File "/Users/zaro/dev/civilcourage-backend/.direnv/python-3.6.1/lib/python3.6/site-packages/aioopenssl/__init__.py", line 444, in _read_ready
    data = self._sock.recv(self.MAX_SIZE)
  File "/Users/zaro/dev/civilcourage-backend/.direnv/python-3.6.1/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1516, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/Users/zaro/dev/civilcourage-backend/.direnv/python-3.6.1/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1371, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')
```

The message is send and received successfully, and everything works as expected. But still this seems strange effect.

I installed the latest available version from pip. Here the versions of aiohttp packages I have:
 - aiofcm (0.4)
 - aiohttp (2.0.7)
 - aioopenssl (0.3.1)

**Comment by Fatal1ty** [comment]
Hi @zaro this error does not affect the sending of notification messages via aiofcm and it is in fact an aioopenssl issue https://github.com/horazont/aioopenssl/issues/2 So I just added ignoring of this error.

**Comment by zaro** [comment]
Thanks for the quick fix. I noticed it doesn't affect the message delivery
but I actually thought its some underlying problem with connection
handling, hence the report.
