### ISSUE TITLE
FCM.pool.MAX_ATTEMPTS

### ISSUE THREAD

**Issue by atolia** [Fatal1ty/aiofcm#8]
Hi, 
Is the var FCM.pool.MAX_ATTEMPTS usable?
I want to reduce attempts to 1 how can I do this?

**Comment by Fatal1ty** [comment]
Hello

For now there is not way dot do this until someone change this logic like the one [here](https://github.com/Fatal1ty/aioapns/pull/11)

You are free to make a pull request and then I release a new version.

**Comment by holyachon** [comment]
@Fatal1ty Hello. I opened PR about this issue.
Please check it at your convenience :)

**Comment by Fatal1ty** [comment]
@holyachon Thank you! I'll check it as soon as I get to my laptop.

**Comment by Fatal1ty** [comment]
Fixed in [1.4](https://github.com/Fatal1ty/aiofcm/releases/tag/v1.4).
